# Site settings
title: >
  Göttinger Biergarten am Kehr - Biergarten im naturgeschützten
  Naherholungsgebiet mitten im Wald
email:
description: >

  baseurl: "https://goettinger-biergarten.de"

# Build settings
markdown: kramdown
