# Site settings
title: >
  Göttinger Biergarten am Kehr mitten im Wald
email:
description: >
  Genieße den Kehr, gönn dir ein frisch gezapftes Bier. Iss eine leckere
  Bratwurst an Sonn- und Feiertagen. Wir freuen uns auf dich.

baseurl: "https://goettinger-biergarten.de"

# Build settings
markdown: kramdown
