# Site settings
title: >
  Quintar GMBH - Personalberatung Industrie, Handel, Banken,
  Dienstleistung und dem öffentlichen Sektor
email: info@quintar-personal.de
description: >
  Qualitativ hochwertige Personalberatung - seit 2007 erfolgreich
  Personalvermittlung, Zeitarbeit, Unterstützung von Bewerbern bei der Jobsuche
  sowie Beratung rund um das Thema Persona
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://quintar-personal.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
