# Site settings
title: >
  Biergarten am Kehr mitten im Stadtwald in Göttingen
email:
description: >
  DER Biergarten in Göttingen am Kehr. Gönne dir ein frisch gezapftes Bier. Iss
  eine leckere Bratwurst an Sonn- und Feiertagen. Wir freuen uns auf dich.

baseurl: ""
url: "https://goettinger-biergarten.de"

# Build settings
markdown: kramdown
