# Site settings
title: >
  Göttinger Biergarten am Kehr - Biergarten im naturgeschützten
  Naherholungsgebiet mitten im Wald
email:
description: >
  Genieße den Kehr, gönn dir ein frisch gezapftes Bier. Iss eine leckere
  Bratwurst an Sonn- und Feiertagen. Schau dir beim Waldspaziergang die
  Wildschweine oder das Damwild an, wir heißen dich willkommen.

baseurl: "https://goettinger-biergarten.de"

# Build settings
markdown: kramdown
