#!/bin/bash
VERSION=$(git log -n 1 --pretty=format:"%h")

jekyll build

find _site -iname "*.css" -type f -exec yui-compressor '{}' -o '{}' \;
find _site -iname "*.html" -type f \
     -exec tidy -i -q -w 0 -m --tidy-mark false --drop-empty-elements false \
     --warn-proprietary-attributes false '{}' \;
find _site -iname "*.html" -type f \
     -exec sed -i "s/--VERSION--/$VERSION/g" '{}' \;
find _site -iname "*.xml" -type f \
     -exec tidy -xml -q -m --tidy-mark false '{}' \;
find _site/images/ -type f -regextype egrep -regex ".*\.(png|jpe?g)$" \
     -exec cwebp -q 80 {} -o {}.webp \;

rsync -aHP --delete _site/ root@goettinger-biergarten.de:/var/www/html

jekyll clean
